GET http://localhost:3000/clientes

###

GET http://localhost:3000/inventario

###

DELETE http://localhost:3000/clientes/60db8e85fcb98c23643710aa

###

GET http://localhost:3000/clientes/60da580849bc133938f89970

###
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nombre":"PuroConejoAsiatico",
    "rfc":"ARG12039KIEJ",
    "direccion":"NO SE DONDE ESTOY TOY CHIQUITO",
    "telefono":"99999 la colita se te mueve",
    "contacto":"el palancas le dicen",
    "correo_contacto":"elPalancas@bienparado.com"
}
###
POST http://localhost:3000/inventario
Content-Type: application/json

{
    "nombre":"Lamina",
    "descripcion":"calibre 14",
    "cantidad":12
}


###
POST http://localhost:3000/api/comidas
Content-Type: application/json

{
    "nombre":"Manzana",
    "cantidad":105
}

###
GET http://localhost:3000/api/comidas

###
POST http://localhost:3000/api/ordenesCompra
Content-Type: application/json

{
    "line":225544,
    "partNumber":16698,
    "description":"dos cuyos",
    "deliveryDateTime":"un dia no muy lejano",
    "quantity":9999,
    
    "unitPrice":234.21,
    "amount":39
}

###
GET http://localhost:3000/api/ordenesCompra

###
POST http://localhost:3000/api/piezas
Content-Type: application/json

{
    "nombreCliente":"Exacolor",
    "piezaNum":105,
    "ppb":16
}